TT#42659 Another attempt to fix for "Delete" button in repoapi docker info page
Commit 39744330b3273dd3647723c638fff94706165917 wrongly added code to call
request.delete() with more than one argument:

  response = requests.delete(url, headers)
  TypeError: delete() takes 1 positional argument but 2 were given

Change-Id: I65b82d9ccef33b295d009b00461f9eeca2da0827