TT#121955 add validate_templates test
https://django-extensions.readthedocs.io/en/latest/validate_templates.html

* add missing optional requirement
> django_filters/templates/django_filters/rest_framework/crispy_form.html: TemplateSyntaxError 'crispy_forms_tags' is not a registered tag library. Must be one of:
> admin_list
> admin_modify
> admin_urls
> assets
> cache
> debugger_tags
> highlighting
> i18n
> import_export_tags
> indent_text
> jsonify
> l10n
> log
> rest_framework
> static
> syntax_color
> tz
> widont
> CommandError: 1 errors found

Change-Id: I6e425cd9dfde112c64143dae3350dce5839311b7