Update patch set 1
Patch Set 1:

> > > why is this failing??
 > >
 > > when I ran docker test locally for your review it works ok. May
 > be
 > > some issue with python library versions?
 > 
 > but that can't be the case as docker is the same.
 > 
 > Error says
 > 
 > DistutilsFileError: could not create '/results/jbi_files/release-tools-runner':
 > No such file or directory
 > 
 > so may be some cleanup happens during test?

this breaks things 

    def tearDown(self):
        if os.path.exists(settings.JBI_BASEDIR):
            shutil.rmtree(settings.JBI_BASEDIR)

as 'jbi_files' subfolder is removed while it's needed by other tests

Patch-set: 1
Reviewer: Sergii Kipot <1000020@85315e57-5f03-49c3-83f8-201ae2313a75>
Label: Verified=0