TT#96400 repoapi: fix structlog use
* complex values need to be string or be produce
  errors like:
> amqp.exceptions.FrameSyntaxError: Table type <class 'repoapi.models.jbi.JenkinsBuildInfo'> for key b'instance' not handled by amqp.

Change-Id: I74ce92b56660cfd9158eff1364c82c4dba2fc081