MT#56231 gerrit: fix default today format
task expects YYYY-MM-DD format

> (venv_prod) root@repoapi2:/usr/share/repoapi# ./manage.py gerrit cleanup --weeks=4
> [...]
>   File "/usr/share/repoapi/gerrit/tasks.py", line 35, in cleanup
>     today = date.fromisoformat(today)
> ValueError: Invalid isoformat string: '2023-12-19T12:39:58.364626'

Change-Id: If635b36d6fb579a7823522aef6e41f2d53eb1823