TT#43813 hotfix: move code from task to utils
Tasks should deal only with serialize/de-serialize parameters
work need to be external so it can be tested easily

* don't call a task directly in tests that causes:

> ======================================================================
> ERROR: test_hotfixreleased (hotfix.test.test_hotfix_released.TestHotfixReleased)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/code/venv_dev/lib/python3.7/site-packages/kombu/utils/objects.py", line 42, in __get__
>     return obj.__dict__[self.__name__]
> KeyError: 'backend'

Change-Id: I620f10d5c58563cc4af2898429bbe1a9a60007b5