MT#62714 Latest Django release from 3.2 series
> https://docs.djangoproject.com/en/3.2/releases/3.2.25/
> https://docs.djangoproject.com/en/3.2/releases/3.2.24/
> https://docs.djangoproject.com/en/3.2/releases/3.2.23/
> https://docs.djangoproject.com/en/3.2/releases/3.2.22/
> https://docs.djangoproject.com/en/3.2/releases/3.2.21/
> https://docs.djangoproject.com/en/3.2/releases/3.2.20/
> https://docs.djangoproject.com/en/3.2/releases/3.2.19/

* django-import-export: lock version to lower than 4.0
  or we get an error
  > https://github.com/django-import-export/django-import-export/commit/745039381cc7c9f61281f4dc76df9f3b48e35df7

> value = datetime.datetime(2022, 6, 2, 10, 19, 28, tzinfo=<UTC>)
> datetime_format = '%Y-%m-%d %H:%M:%S'
>
>     def format_datetime(value, datetime_format):
>         # handle correct formatting of dates
>         # see https://code.djangoproject.com/ticket/32738
> >       format_ = django.utils.formats.sanitize_strftime_format(datetime_format)
> E       AttributeError: module 'django.utils.formats' has no attribute 'sanitize_strftime_format'
>
> /usr/local/lib/python3.11/dist-packages/import_export/widgets.py:25: AttributeError

* t/Dockerfile: add missing iproute2
  Some Makefile dev rules are using ``ip`` command

Change-Id: I67463cae05dfbad763013319c0d28df3133e36a6