TT#134250 remove yuicompressor since is no longer provide by pip
* remove dh-systemd, no longer necessary
* add libsasl2-dev as dependency fixing pip build of python-ldap

> Modules/LDAPObject.c:16:10: fatal error: sasl/sasl.h: No such file or directory
>    16 | #include <sasl/sasl.h>
>       |          ^~~~~~~~~~~~~
> compilation terminated.
> error: command '/usr/lib/ccache/x86_64-linux-gnu-gcc' failed with exit code 1
> ----------------------------------------

Change-Id: I0c6265bfb607e77f74a85f094dd03b3017532d73